### ISSUE TITLE
Action fails to deploy in one repo, and deploys successfully on another repo while still leaving the website empty

### ISSUE THREAD

**Issue by Gioele-Bencivenga** [HaxeFlixel/game-jam-template#3]
Hi, I'm trying to use the workflow in this repo for hosting my projects and I've been running into some issues.

I [changed the yaml](https://github.com/Gioele-Bencivenga/TilemapGen/blob/main/.github/workflows/main.yml#L19) in order to download the additional libraries required by my projects. I have no experience in this and only did this following advice, so it might be a cause of my issues.

At the moment I have a repo with HaxeFlixel, Echo and HaxeUI which seems to skip the deploy step [here](https://github.com/Gioele-Bencivenga/TilemapGen/runs/1303184773?check_suite_focus=true).

I tried reproducing the issue in another project that only uses HaxeFlixel and Echo, but this time [everything seemed to go smoothly](https://github.com/Gioele-Bencivenga/SpaceShooter/runs/1299024439?check_suite_focus=true).
When visiting https://gioele-bencivenga.github.io/TilemapGen/ or https://gioele-bencivenga.github.io/SpaceShooter/ no page is found.

Another thing I suspect might be causing issues is the static website I'm hosting on github pages, however I wouldn't know how to go about that since I'd like to keep the site up.

Unfortunately I don't have any experience with github actions so I'm pretty lost, any pointer or suggestion is appreciated!

**Comment by Gama11** [comment]
Have you checked the GitHub pages section of the repo settings? For this repo it looks like this:

![image](https://user-images.githubusercontent.com/2620907/97104056-042ccf00-16b1-11eb-8f4e-4dacea3805e5.png)

**Comment by Gioele-Bencivenga** [comment]
Thanks a lot, I had no clue about this step, must have missed it!

I selected the gh-pages branch as the source for [this project](https://github.com/Gioele-Bencivenga/SpaceShooter/settings) and it has been correctly published which is fantastic.

Unfortunately in my second project I see no gh-pages branch when I extend the dropdown, just main, custom and none.
![image](https://user-images.githubusercontent.com/8895937/97105750-5374fe80-16b5-11eb-98aa-16ab3f9532d6.png)

I tried selecting all possible options but none of them ends up correctly displaying the project at the address.
Any clue what might be the issue with this?

**Comment by Gioele-Bencivenga** [comment]
I [tried changing the last line of the yaml from master to main](https://github.com/Gioele-Bencivenga/TilemapGen/commit/657ba6486e2693dcc8d74156c12c339a97a8ba83) since my main branch is named main instead of master, and it worked!

~~Selecting gh-pages as the source in the settings shows the flixel preloader but breaks at 0%, while selecting the main branch as the source correctly displays the project for some reason.~~

Selecting the gh-pages branch correctly displays the project.
