### ISSUE TITLE
Potentially outdated ubuntu path

### ISSUE THREAD

**Issue by chosencharacters** [HaxeFlixel/game-jam-template#4]
Hey everyone

I've been trying to run this with several different fresh new projects over the last month, but my most recent I'm getting this error when running

```Run HaxeFlixel/setup-flixel@master
Installing Haxe Dependencies
  [global] /home/runner/haxe
  > lix install haxe stable --global 
  Looking up Haxe version "stable" online
    Resolved to official release 4.2.1. Downloading ...
  Downloading Haxe: official release 4.2.1
  -> Done!
    ... download complete!
  > sudo apt install neko 
  
  WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
  
  Reading package lists...
  Building dependency tree...
  Reading state information...
  The following additional packages will be installed:
    libgail-common libgail18 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common
    libmariadb3 libmbedcrypto3 libmbedtls12 libmbedx509-0 libneko2
    mariadb-common
  Suggested packages:
    gvfs libapache2-mod-neko neko-dev
  The following NEW packages will be installed:
    libgail-common libgail18 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common
    libmariadb3 libmbedcrypto3 libmbedtls12 libmbedx509-0 libneko2
    mariadb-common neko
  0 upgraded, 12 newly installed, 0 to remove and 3 not upgraded.
  Need to get 3087 kB of archives.
  After this operation, 10.6 MB of additional disk space will be used.
  Get:1 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libgtk2.0-common all 2.24.32-4ubuntu4 [126 kB]
  Get:2 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libgtk2.0-0 amd64 2.24.32-4ubuntu4 [1791 kB]
  Get:3 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libgail18 amd64 2.24.32-4ubuntu4 [14.7 kB]
  Get:4 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libgail-common amd64 2.24.32-4ubuntu4 [116 kB]
  Get:5 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libgtk2.0-bin amd64 2.24.32-4ubuntu4 [7728 B]
  Ign:6 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 mariadb-common all 1:10.3.25-0ubuntu0.20.04.1
  Ign:7 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 libmariadb3 amd64 1:10.3.25-0ubuntu0.20.04.1
  Get:8 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libmbedcrypto3 amd64 2.16.4-1ubuntu2 [150 kB]
  Get:9 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libmbedx509-0 amd64 2.16.4-1ubuntu2 [42.3 kB]
  Get:10 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libmbedtls12 amd64 2.16.4-1ubuntu2 [71.8 kB]
  Get:11 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libneko2 amd64 2.3.0-1 [44.1 kB]
  Get:12 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 neko amd64 2.3.0-1 [553 kB]
  Err:6 http://security.ubuntu.com/ubuntu focal-updates/universe amd64 mariadb-common all 1:10.3.25-0ubuntu0.20.04.1
    404  Not Found [IP: 52.147.219.192 80]
  Err:7 http://security.ubuntu.com/ubuntu focal-updates/universe amd64 libmariadb3 amd64 1:10.3.25-0ubuntu0.20.04.1
    404  Not Found [IP: 52.147.219.192 80]
  E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/m/mariadb-10.3/mariadb-common_10.3.25-0ubuntu0.20.04.1_all.deb  404  Not Found [IP: 52.147.219.192 80]
  Fetched 2916 kB in 0s (17.7 MB/s)
  E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/m/mariadb-10.3/libmariadb3_10.3.25-0ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?```

Seems like the ubuntu link is outdated or misconfigured :x

**Comment by chosencharacters** [comment]
For the record the correct path should be (I think)

`http://security.ubuntu.com/ubuntu/pool/universe/m/mariadb-10.3/mariadb-common_10.3.29-0ubuntu0.20.10.1_all.deb`

It seems like 20.04.01 was deprecated on a cursory glance of [this page](http://security.ubuntu.com/ubuntu/pool/universe/m/mariadb-10.3/)

**Comment by Gama11** [comment]
>I've been trying to run this

"Run this" where, with GH Actions? I don't see any forks of this project on your profile.

**Comment by chosencharacters** [comment]
This is the project I'm working on atm https://github.com/chosencharacters/tactics

**Comment by Gama11** [comment]
>It seems like 20.04.01 was deprecated on a cursory glance

The workflow is running on 20.04.2 because of `ubuntu-latest` in the YML:

https://github.com/chosencharacters/tactics/runs/2579003144#step:1:4

It might be that an explicit `apt update` as mentioned in the error you posted would help:

> Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

However, I don't think that should be required / sounds like some issue with GitHub Actions. Perhaps you can find something about it here: https://github.community/c/code-to-cloud/github-actions/41

**Comment by chosencharacters** [comment]
Has anyone else been able to use the jam template? I guess I'm confused as
to what the next step is from here. apt --update seems to be an automatic
step, not sure how I'd modify the main.yaml to fix this.

In addition, it's likely not working with anyone else. That's just my
guess, though.

**Comment by Gama11** [comment]
Well, yes, the workflow passed on the master branch of the main repo as recently as ~1 month ago:

https://github.com/HaxeFlixel/game-jam-template/runs/2369291454

It even passed on your own fork 12 days ago:

https://github.com/chosencharacters/tactics/runs/2485428946

So whatever the issue with GH actions is, it must be somewhat recent.

**Comment by chosencharacters** [comment]
When making a new clone of the base template repo, does it pass for you?

**Comment by Gama11** [comment]
I just noticed that this happens even on the main flixel repo: https://github.com/HaxeFlixel/flixel/runs/2581164142?check_suite_focus=true

**Comment by Gama11** [comment]
It looks like we should indeed be running `apt update` explicitly in the workflows:

https://github.com/actions/virtual-environments/issues/1757

That issue resulted in an update of the docs on https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners:

![image](https://user-images.githubusercontent.com/2620907/118275006-2445a380-b4c6-11eb-819b-cd4ccff7e094.png)

Previously I was assuming that's something GitHub Actions takes care of.

**Comment by chosencharacters** [comment]
That's what I've been saying man this feels like a deeper haxe issue

**Comment by Gama11** [comment]
None of this has anything to do with Haxe.

**Comment by chosencharacters** [comment]
Yep yea that fix fixed it for me
